# Generated by Django 4.2.4 on 2023-09-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rate",
            name="credit_union",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
